name: Triggers

on:
   push:
     branches:
       - master
   pull_request:
     types:
       - opened
       - synchronize
   schedule:
     - cron: '*/1 * * * *'
   workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print the statement
        run: echo "$GREETING" 

      - name: Print current time
        run: echo "The current time is $(date)"
